---
# ROLE: PHP
#
# DESCRIPTION:
# This role installs PHP and required PHP packages


###############################################################################
################### VARIABLE INITIALIZATION & TASK SETUP ######################
###############################################################################


# Collect a string of required packages, separated by commas
- name: PHP_REQUIRED_PACKAGES set fact from env if possible
  set_fact:
    PHP_REQUIRED_PACKAGES: "{{ lookup('env', 'PHP_REQUIRED_PACKAGES') }}"
  when: lookup('env', 'PHP_REQUIRED_PACKAGES') | default('', true) | trim != ''
- name: PHP_REQUIRED_PACKAGES prompt user input if unset
  pause:
    prompt: "SET PHP_REQUIRED_PACKAGES"
    echo: yes
  register: input
  when: PHP_REQUIRED_PACKAGES is not defined
- name: PHP_REQUIRED_PACKAGES set fact from user input
  set_fact:
    PHP_REQUIRED_PACKAGES: "{{ input.user_input }}"
  when: PHP_REQUIRED_PACKAGES is not defined


###############################################################################
############################ ROLE IMPLEMENTATION ##############################
###############################################################################


# Step 1: Install PHP and necessary PHP packages  with apt

- name: Install PHP and necessary extensions
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ PHP_REQUIRED_PACKAGES }}"
  become: yes